### ISSUE TITLE
Spec QA: Annual contribution notice

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee#104]
Here's a first sketch for the prorate annual contribution flow:

- for annual contributions we could include the renewal date in the "white summary box". Having this information visible will make the options for increasing the contribution clearer.
- we figure you'll have a better clue on the right wording for the two options we need to provide: instant payment of the remainder; wait until next payment.
- The "update contribution" button might not make sense if the user wants to wait until the next payment cycle; we could change the button according to the option picked.

[Open in PenPot](https://design.penpot.app/#/view/bf28f200-e971-11eb-9b24-4c4b7a420f0b?page-id=36a18270-e972-11eb-b4d3-978aa0906fd6&index=0&share-id=6eac2ba0-6f1b-11ec-8da6-c2b142838c8b)

![image](https://user-images.githubusercontent.com/159868/148429443-9e2dcc18-3a71-444c-b5d4-565eea7f51f9.png)

Will's notes on Slack about this:

- The payment is taken once a year, it's just bad UX that makes it look like it's taken in monthly installments
- Originally we only wanted annual contributors to be able to take contributions that were 12 times a monthly contribution (e.g. £12, £24, £36 etc.) so we decided to quote everything as the per month amount even if you were then charged per year
- This is just about annual contributors increasing their contribution and either doing so immediately by paying a one off fee (the prorate) or waiting until the next payment

**Comment by wpf500** [comment]
Looks good :+1:

Comments:
1. We don't have the explanation of where the calculation for the €12 one-off payment comes any more, do you think we don't need it?
2. "Update my contribution next year" probably needs to say "Update my contribution on 10th April 2022" as it won't always be next year (their next payment can be anywhere from 1 to 11 months away). Maybe could be something generic like "Update my contribution on my next payment cycle" but I think the actual date works better.
   - Maybe the text could say "You'll stay on your current contribution until your next payment on 10th April 2022" or something?
3. No need for the "redirected to GC" text
4. I don't think we need the ", for the same period and amount." bit of the text in the box

**Comment by wpf500** [comment]
Oh a couple more:
2. I think the "Update contribution" tex

**Comment by julia-hildebrand** [comment]
@rlafuente I don't have any comments here, I understand too little ;-) I think Will has this one covered.

**Comment by wpf500** [comment]
Closing as changes have been merged
