### ISSUE TITLE
Remove HTML when copy-pasting into editable fields 

### ISSUE THREAD

**Issue by saschafoerster** [beabee-communityrm/beabee#110]
When copy-pasting into the field Subtitle of the "Join page"  at /settings/content", some HTML-content is not filtered out and can't be deleted afterwards. I copied some lines from Github into this field, and then it became black and had a monospaced font. This can't be removed. 

<img width="716" alt="Bildschirmfoto 2022-01-28 um 22 53 41" src="https://user-images.githubusercontent.com/1153741/151627032-34807e7b-08b2-4b44-8b9e-f6c1871c605a.png">

**Comment by saschafoerster** [comment]
Frontend: 
<img width="487" alt="Bildschirmfoto 2022-01-28 um 22 57 21" src="https://user-images.githubusercontent.com/1153741/151627118-43e2e008-182c-41cd-b618-8acdd2829f87.png">

**Comment by wpf500** [comment]
Yeah definitely agree this is a problem at the moment, will add it to our backlog :+1:
