### ISSUE TITLE
Spec QA: Steps navigation in callout creation flow

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee#112]
_(moving the [Trello discussion on the steps navigation](https://trello.com/c/8t8V2Eck/388-%F0%9F%8E%A8-changes-for-create-new-call-out-page-navigation) to github)_

![image](https://user-images.githubusercontent.com/122730/153172099-3c24c635-b658-4620-8657-2b27a525f110.png)

We've added a screenshot of the revised step navigation. We propose to remove the visual indicator of completion of the step while it's still not clear what we want to signal to the user:

    does it mark the completion of mandatory fields in each step? Some steps are optional, like social sharing and Mailchimp sync
    is it a progress indicator? if so, does that mean we'll only let the user advance to the next step once all mandatory fields are completed?

We think it would also be helpful to:
- sort out which fields in the callout creation need to be mandatory
- to which fields we can provide defaults
- how to mandatory fields and defaults work together --> this links back to the [Slack thread ](https://beabee-communityrm.slack.com/archives/C01CXSGASF6/p1642677761012800)from last week :)

---

**Will Franklin:** @aiscarvalho @rlafuente I think we should enforce the steps for creating a callout (i.e. you can't just jump past a step), so the completion mark becomes a mark of progress.

I think journalists are very used to this sort of flow for publishing any content so it won't be a barrier for them, and we can provide sensible defaults so they can go through the steps quickly.

**Comment by aiscarvalho** [comment]
@wpf500 we [updated the spec](https://design.penpot.app/#/view/e35a4dc0-1ae2-11ec-9c71-4a8af25a7bed?page-id=4a449480-5910-11ec-8ccc-4b86b12c67d6&section=interactions&index=0&share-id=50d8b780-89c7-11ec-b79c-9eafb5cb1e0f) to include the completion marks in the steps during the creation flow. When editing an existing callout, the step navigation is the same but without the completion marks.

Attaching here a screenshot of the last page of the spec, detailing the navigation workings:

![image](https://user-images.githubusercontent.com/122730/153250095-453bb573-2afc-43b2-b184-71f209a43da4.png)

**Comment by wpf500** [comment]
:+1: looks good to me

**Comment by wpf500** [comment]
It looks like this is already marked as done in Trello, so we can close this?

**Comment by aiscarvalho** [comment]
Yes!
