### ISSUE TITLE
QA: Edit callout interface

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee#114]
The editing mode is in **page 19** of the [Callout spec](https://design.penpot.app/#/view/e35a4dc0-1ae2-11ec-9c71-4a8af25a7bed?page-id=4a449480-5910-11ec-8ccc-4b86b12c67d6&section=interactions&index=0&share-id=50d8b780-89c7-11ec-b79c-9eafb5cb1e0f).

We reused as much as possible from the creation interface. When editing:
- the step navigation has no completion/progress indicators
- the navigation buttons between steps convert to back/next (instead of Back/Continue)
- a new button is introduced to "Update". When clicking update the user closed the edit mode and returns to the callout overview page.
- the callout title is displayed, instead of "Create a new callout"

@wpf500 what are your thoughts on the use or need of the "Save draft" while editing a non-draft callout?
It could be useful to have a button to convert a scheduled callout into "draft mode", so that could be its purpose. But we'd like your input there.

![Page 16](https://user-images.githubusercontent.com/122730/153449926-01c3a825-53e4-417b-978e-7848cd5e79c0.png)

**Comment by wpf500** [comment]
@aiscarvalho I think we should support reverting a live or scheduled callout to draft, although I think we might want to add a warning to the user if they try to revert a live callout that already has responses (as this would hide the callout from users again).

The backend doesn't currently support having a different live and draft callout. I think for MVP we won't support previewing updates, so the options for a non-draft callout would be either revert to draft or update

**Comment by wpf500** [comment]
Only other comment is just a minor change to the callout actions. A draft callout will have "Preview", not "View". I think a scheduled callout should also say "Preview" rather than "View"

![image](https://user-images.githubusercontent.com/2084823/153585846-d22f16d6-a6a7-42a0-855a-2aa1209ff7de.png)

**Comment by TobiasHauswurz** [comment]
Review for page 19: 

Looks very good to me. What confuses me a bit is the Update button: 

- What's the difference between "Update" and "Save Draft"? 
- The position of the "Update" button indicates to me, that I would have to click on "Update" to save **after** making my edits in one of the sections and **before** clicking on "Next" or jumping to another section in the side bar. But when it's closing the whole editing process I would maybe place it somewhere else, for example somewhere where the "Save Draft" button is.

**Comment by julia-hildebrand** [comment]
Looking good to me. The details on all these things will need some more user testing than we are used to so far ... We should do some testing of the callouts when the first version is implemented.

**Comment by wpf500** [comment]
@aiscarvalho I think this can be closed now?

**Comment by rlafuente** [comment]
There's Tobi's review points, which we'll address tomorrow and close this once they're dealt with

**Comment by rlafuente** [comment]
The Edit options are now updated following Tobi's suggestion to place Update on the options area, and Will's point about preview not being available and needing an option to revert to draft:

![image](https://user-images.githubusercontent.com/159868/155510818-026eef99-9711-4120-a97e-8a587be63bd1.png)

If you think it's addressed, this issue is ready for closing!

**Comment by wpf500** [comment]
:+1:
