### ISSUE TITLE
QA: Response callout page

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee#116]
Here's a first draft spec for the [response callout page](https://design.penpot.app/#/view/e35a4dc0-1ae2-11ec-9c71-4a8af25a7bed?page-id=80a83000-8349-11ec-b868-f579dbfb6f82&section=interactions&index=0&share-id=50d8b780-89c7-11ec-b79c-9eafb5cb1e0f). Some quick notes:

- the labels/questions are set in bigger type (same style as headers level 4), all other form elements are the same
- ~~departing from the legacy app, we added the final thank title and note as a success notification. We think it should only be visible upon submission.~~ in view of the feedback we updated the spec and the thank you is no longer a success notification
- the sharing link should only appear for callouts that are open and visible (as opposed to hidden)
- it would be a nice-to-have to include a paragraph about the results of the callout. In the spec we added a link to an article done summarising results.

What's missing:
- mobile layout, we would add this once we figure out the information and details in page
- how we show multiple answers, in callouts that allow multiple answers

![image](https://user-images.githubusercontent.com/122730/154115806-5f133387-d7a9-41f4-b923-d3a48c387690.png)

**Comment by TobiasHauswurz** [comment]
Hey, this is the feedback from our session with Lucas. We didn't have enough time to review every page. 

General: 

Once you have answered a call-out
- might need separate page when someone is completed
> success page vs. seeing the full page and edit things again > move on in the journey: Focus on what’s next rather than going back > focus should be on sharing, thank you, respond to another call-out 
- Description for intro would be useful 
- Open question: Do they need to see their response at all? > Reason= transparency, but might not need to be in your face 
- See full page as designed now with the answers (greyed out) 
- Open question: Do they really need to edit questions? > don’t see use case for this
 
- Don’t think of the previous callout design as consciously build
- We should maybe think about different pages instead of different stages of the same page

**Screen 1: Response, logged in user**

- Don’t want to encourage people to answer anonymously > benefit to them not clear of being the one or the other
- Where/When do you allow people to decide whether to stay anonymous?

- Form could be more distinct in separating questions sections using block design or separators between questions > too dense

- Form design more modern?

- Required Questions might need an indicator why they are required
 
- The “Open” indicator looks a bit like a button


**Screen 2: Thank you for responding**

- Headline text might be: You replied on <date>. If you’d like to view or update your response, please do so below. 

- Position of the icons: icons on the right feel a bit hidden (share, Open, you replied)

- Edit response button > move to the top 

- When you already have submitted answers you can’t logout and then change answers to anonymous 
> Either they can’t change to anonymous 
> Or they need to be logged in to change to anonymous 


**Screen 3: Add another response**

A use case for submitting multiple answers is: rolling call-out, e.g. looking for multiple ideas, tip-off, story idea

- based on the use case the “you replied” piece might not be useful here and should be different

- same for showing previous answers below

- instead of “add a response” > “Submit another response”

**Comment by aiscarvalho** [comment]
We're including the original notes so we can address all of them. We went ahead to update some parts of the spec and are including screenshots for quick reference.

Thank you so much for the detailed feedback, we agree with almost all the suggestions and didn't go further design wise to keep things grounded for the MVP.
Maybe we can chat through these in a call, tomorrow?

**General:**
- _might need separate page when someone is completed_
    - what infos should be in this after completion page? and what infos shouldn't be there? for example, should this page display the callout image and description?
- _Description for intro would be useful_
    - we need clarification for this suggestion :)
- _Open question: Do they need to see their response at all? > Reason= transparency, but might not need to be in your face_
    - we think it's important that we show the user hers/his replies. We can try a more compact layout or have it collapsed, depending on what is technically feasible. ![](https://i.imgur.com/iPNujvC.png)
- _See full page as designed now with the answers (greyed out)_
    - Updated, all answers are grayed out ![](https://i.imgur.com/og0mzUx.png)
- _Open question: Do they really need to edit questions? > don’t see use case for this_
    - We had that in the requirements but if there's no use case for updating replies we'll take it out (and update the callout creation form accordingly). This change reduces a lot of the complexity in the callout stages. Should we take it out?
- _Don’t think of the previous callout design as consciously build_
    - We designed with the MVP constraints in mind. If we have leadway we can definitely explore other possibilities. Slides, dividing the questions in different screens, is the first thing that comes to mind though we're not sure if that's possible to set up in the form builder. Some tech input would be great before we go further.
- _splitting the answer callout in different pages instead of different stages of the same page._
    - Do you have clues on how to slip it? We'd also welcome some tech input on this change since we foresee some added complexity.

**Screen 1**
- _Don’t want to encourage people to answer anonymously_
    - updated: we moved the text and link to logout to the left side, when the user is logged in. We kept in the central column when for logged out users, to encourage them to login 
    - ![](https://i.imgur.com/doomOBH.png)
- _Where/When do you allow people to decide whether to stay anonymous?_
    - In the callout creation - page 4 of the [callout creation spec](https://design.penpot.app/#/view/e35a4dc0-1ae2-11ec-9c71-4a8af25a7bed?page-id=4a449480-5910-11ec-8ccc-4b86b12c67d6&section=interactions&index=0&share-id=50d8b780-89c7-11ec-b79c-9eafb5cb1e0f) (it's also here the admin can decide if the user can or cannot update hers/his responses) ![](https://i.imgur.com/zNkpVON.png)
- _Form could be more distinct in separating questions sections using block design or separators between questions > too dense_
    - We'd welcome some technical input: can the admin indicate blocks/groups of questions? Otherwise we don't have a clear criteria to organise/split questions without risking separating content that should be show together.
- _Form design more modern?_
    - Again, some technical input would be great as we don't want to steer from MVP goals at this stage.
- _Required Questions might need an indicator why they are required_
    - Do you mean some explanatory text as to why they're required?
- _The “Open” indicator looks a bit like a button_
    - Good call! It's updated: ![](https://i.imgur.com/irI16HM.png)

**Screen 2**
- _Headline text might be: You replied on . If you’d like to view or update your response, please do so below._
    - With the other updates we're not sure where to fit this bit of text. Should it be a part of the thank you note? Should it replace the help text shown near the "update responses"? We might not need to change anything if updating responses is removed, as suggested in the general comments. ![](https://i.imgur.com/AWaRJ2V.png)
- _Position of the icons: icons on the right feel a bit hidden (share, Open, you replied)_
    - Updated. We moved the infos shown on the right to the central column, below the callout title.
- _Edit response button > move to the top_
    - Moved. (this button will also if there's no option to update responses)
- _When you already have submitted answers you can’t logout and then change answers to anonymous_
    - Updated. We removed that link (though if the callout allows for anonymous replies the user can indeed logout and reply anonymously).
- _Either they can’t change to anonymous. Or they need to be logged in to change to anonymous_
    - Is this related to the comment above or something else to consider?

**Screen 3**
- _based on the use case the “you replied” piece might not be useful here and should be different_
    - This won't be an issue as, from a comment above, we moved this bit of text and logout link to the left
- _same for showing previous answers below_
    - This bit will depend on another comment above, about splitting pages and moving the user answers to a different page
- _instead of “add a response” > “Submit another response”_
    - Button text updated!

**Comment by wpf500** [comment]
Wow lots of comments, thanks for taking the time to reply so thoroughly!

I think anything to do with how the form looks we should ignore for now, we're not in a place to do a lot of work on that for MVP. I agree with the changes you've made so far and think we should move this design task to done so this doesn't keep growing as a task. A few things are bound to come up during the implementation phase in any case so we can revisit then.

Nice work :+1:

**Comment by aiscarvalho** [comment]
We added some notes to the spec, documenting future improvements that were suggested but might not be feasible for MVP and document parts of the UI that weren't clear. We can address some of those once implementation takes place.

Yay for team work!
