### ISSUE TITLE
Wireframes: Membership builder 

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee#117]
Here's the first take on how the forms would work. Initial questions:

- We tried to simplify as much as possible -- is there anything vital missing?
- Likewise is there something that could be simplified further?

Curious about your feedback!

## Step 1: Contributions

![image](https://user-images.githubusercontent.com/159868/155297138-af96a012-2ca8-4e31-8490-68bdf2e27c32.png)

## Step 2: Personal details

![image](https://user-images.githubusercontent.com/159868/155297170-81a6e4ab-538c-442c-adb5-1914f02a3152.png)

**Comment by rlafuente** [comment]
Super clear! Here's a new take:

![image](https://user-images.githubusercontent.com/159868/160617058-dafbe505-0777-4cce-a681-b59c707a948e.png)

We'll work on widget designs+placement later, for now let's just settle on what should be there.

And yes, 100% with you regarding the other steps of the membership builder. We'll take care of the remaining wireframes now!

**Comment by aiscarvalho** [comment]
Adding here the wireframes for welcome email, goodbye email, welcome message and payment provider connection ([penpot link](https://design.penpot.app/#/view/167be840-9008-11ec-bd38-efdb6fa63305?page-id=4e29b270-b03a-11ec-8735-b3cbc25196fd&section=interactions&index=0&share-id=43995b00-b4ca-11ec-862a-da95c03a630b)):

![image](https://user-images.githubusercontent.com/122730/161734362-62a157fc-2fbb-4952-abe0-20e7276ffa79.png)

---

![image](https://user-images.githubusercontent.com/122730/161734274-3aa84418-26bf-4be5-9e17-e1d83c4606c3.png)

---

![image](https://user-images.githubusercontent.com/122730/161734466-1ade96b6-97d9-4d51-bdb7-2d890a0a0641.png)

**Comment by wpf500** [comment]
Looks good :+1:
