### ISSUE TITLE
QA: Improve search box UI

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee#125]
![image](https://user-images.githubusercontent.com/122730/156595672-d25e8dbc-7307-4231-9bb6-c1a4c5b09b87.png)

So, we added the searchbox to the [Design system spec](https://design.penpot.app/#/view/1555ffb0-ea21-11eb-9b24-4c4b7a420f0b?page-id=1555ffb1-ea21-11eb-9b24-4c4b7a420f0b&section=interactions&index=0&share-id=39e5c0b0-4145-11ec-a943-23056af0be2f), as a more general component. Improvements:

- to search the user can click Enter (keyboard) but can also click the magnifying glass icon
- once the searchbox has content, the clear (x) button becomes visible
- the clear button clears the searchbox and search results

We added to the admin Contact list spec, to show how we can display the number of results with the table. Screenshots attached or [see pages 6,7,8](https://design.penpot.app/#/view/3342c4a0-46c8-11ec-8508-6194167bb409?page-id=3a291521-3d7d-11ec-a943-23056af0be2f&section=interactions&index=0&share-id=85a1a100-5846-11ec-a5ae-e949c75b760d)

![image](https://user-images.githubusercontent.com/122730/156595520-ebc96b05-fd41-4592-af64-e63a62dbaf46.png)

![image](https://user-images.githubusercontent.com/122730/156595571-feb8ebd6-d9cf-4ddb-ae7c-4061ccb02ba7.png)

Hope these small tweaks make sense!

**Comment by basilesimon** [comment]
https://github.com/beabee-communityrm/beabee-frontend/pull/122
