### ISSUE TITLE
Bug: Callout content component is not an input component

### ISSUE THREAD

**Issue by JumpLink** [beabee-communityrm/beabee#347]
I just exported one of my Callout forms as json to use it for validation tests and I just realised that the Callout component of type `content` has the property `input: false`. Is this a bug?

**Comment by wpf500** [comment]
I don't think it's a bug, the `content` type is basically just HTML content to be displayed to the user. I can imagine the types in beabee-common are wrong though

**Comment by JumpLink** [comment]
Oh and I thought this was a form where users are allowed to use formatting (WYSIWYG), then I implemented it wrong, thanks.

Then I will also make "content" a separate type in common. Currently "content" is a possible value of `InputCalloutComponentSchema["type"]`, probably I had entered that.
